import { describe, expect, it } from 'bun:test'
import { parseYarnLock } from '../../../src/ingestion/lockfile/yarn-lock'
import { parsePnpmLock } from '../../../src/ingestion/lockfile/pnpm-lock'
import { parseBunLock } from '../../../src/ingestion/lockfile'

describe('parseYarnLock', () => {
  it('parses v1 blocks with ranges and scoped names', () => {
    const content = `# THIS IS AN AUTOGENERATED FILE
"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz"
express@^5.2.1:
  version "5.2.1"
  resolved "https://registry.yarnpkg.com/express/-/express-5.2.1.tgz"
"qs@npm:^6.5.2":
  version "6.5.2"
`
    const deps = parseYarnLock(content)

    expect(deps).toContainEqual({
      ecosystem: 'npm', name: '@babel/code-frame', requestedVersion: '^7.0.0', resolvedVersion: '7.12.11', path: 'node_modules/@babel/code-frame',
    })
    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'express', requestedVersion: '^5.2.1', resolvedVersion: '5.2.1', path: 'node_modules/express',
    })
    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'qs', requestedVersion: '^6.5.2', resolvedVersion: '6.5.2', path: 'node_modules/qs',
    })
  })
})

describe('parsePnpmLock', () => {
  it('parses v9 importers and packages', () => {
    const content = `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      express:
        specifier: ^5.2.1
        version: 5.2.1
    devDependencies:
      typescript:
        specifier: ^5.4.0
        version: 5.4.2
packages:
  express@5.2.1(debug@4.4.0):
    resolution: {integrity: sha512-aaa}
  '@babel/code-frame@7.12.11':
    resolution: {integrity: sha512-bbb}
`
    const deps = parsePnpmLock(content)

    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'express', requestedVersion: '^5.2.1', resolvedVersion: '5.2.1', path: 'node_modules/express',
    })
    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'typescript', requestedVersion: '^5.4.0', resolvedVersion: '5.4.2', path: 'node_modules/typescript',
    })
    expect(deps).toContainEqual({
      ecosystem: 'npm', name: '@babel/code-frame', requestedVersion: undefined, resolvedVersion: '7.12.11', path: 'node_modules/@babel/code-frame',
    })
    expect(deps).not.toContainEqual(expect.objectContaining({ name: 'debug' }))
  })
})

describe('parseBunLock', () => {
  it('parses the packages map', () => {
    const content = `version: "1.2"
packages:
  express@5.2.1:
    dependencies:
      qs: "6.5.2"
  lodash@4.17.21:
    bin: {}
`
    const deps = parseBunLock(content)

    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'express', requestedVersion: undefined, resolvedVersion: '5.2.1', path: 'node_modules/express',
    })
    expect(deps).toContainEqual({
      ecosystem: 'npm', name: 'lodash', requestedVersion: undefined, resolvedVersion: '4.17.21', path: 'node_modules/lodash',
    })
  })
})
